version: '3.3'
services:

  app:
    container_name: "app"
    restart: always
    image: dream_project
    ports:
      - "8080:8080"
    depends_on:
      - db
      - prometheus
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      #      comando para armazenar os dados persistidos
      - ./init/db:/var/lib/postgresql/init
      #      comando para criar as tabelas via SQL
      - ./init:/docker-entrypoint-initdb.d
  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './src/main/resources/prometheus.yml:/etc/prometheus/config.yml'

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /src/main/resources:/etc/src/main/resources
    depends_on:
      - prometheus