name: Code Analysis with detekt

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup detekt
        id: setup_detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: v1.23.4
          add_to_path: false

      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.4

                  
      - name: Run detekt
        run: /opt/hostedtoolcache/detekt-cli/1.23.4/all/detekt-cli-1.23.4/bin/detekt --version
