name: Install detekt

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup detekt
        id: setup_detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: v0.15
          add_to_path: false
      - name: Run detekt
        run: ${{ steps.setup_detekt.outputs.detekt }} --version
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.4
